root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "templ generate && npm run build && go build -o ./tmp/main ."
  bin = "tmp/main"
  args_bin = []
  delay = 1000
  exclude_dir = ["node_modules", "tmp", "dist", "public", "static"]
  exclude_file = []
  exclude_regex = ["_templ.go", "_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "ts", "scss", "html", "templ"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
