version: "3.9"

services:
  mesh:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: mesh
    ports:
      - "10084:8000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
